# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      mkdir "D:\test\copyrepo"
      $sourceURL = "https://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@github.com/Naveen-LinuxAwsguy/Mirroring.git"
      $destURL = "https://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@github.com/naveenvasudevan46/mirroring.git"
      
      
      Set-Location "D:\test\copyrepo"
      git clone --mirror $sourceURL
      
      Set-Location "D:\test\copyrepo\mirroring.git"
      Write-Host "*****Git removing remote origin****"
      git remote rm origin
      
      
      Write-Output "**Git remote add*"
      git remote add --mirror=fetch origin $destURL
      
      Write-Output "**Git fetch origin*"
      git fetch $destURL
      
      Write-Output "**Git push to Azure Repos*"
      git push origin --all -f